###
GET http://localhost:3306/api/shopping/ 
authtoken:
Content-Type: application/json

###
POST http://localhost:3306/api/shopping/ 
Content-Type: application/json
{
    "name" : "",
    "createddate": ""
}

###
PUT GET http://localhost:3306/api/shopping
Content-Type: application/json
{
    "id": "",
    "name": "",
    "createddate": ""
} 

###
DELETE GET http://localhost:3306/api/shopping/1 