###
GET http://localhost:3306/api/user/ 
authtoken:
Content-Type: application/json

###
POST http://localhost:3306/api/user/signup 
Content-Type: application/json
{
    "username" : "",
    "password": "",
    "email":"",
    "phone":"",
    "country":"",
    "city":"",
    "postcode":"",
    "name":"",
    "address":"",
}

###
PUT http://localhost:3306/api/user
Content-Type: application/json
{
    "username" : "",
    "password": "",
    "email":"",
    "phone":"",
    "country":"",
    "city":"",
    "postcode":"",
    "name":"",
    "address":"",
} 

###
DELETE http://localhost:3306/api/user/1

###
POST http://localhost:3306/api/user/signin
Content-Type: application/json
{
    "username" : "",
    "password": "",
} 